services:
  - type: web
    name: rowdy-cup-api
    env: node
    rootDir: .
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
    healthCheckPath: /_health
    autoDeploy: true