services:
  - type: web
    name: rowdy-cup-v3-cursor
    env: node
    plan: starter
    buildCommand: |
      npm install --production=false
      npm run build:server
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: VITE_API_URL
        value: https://rowdy-cup-v3-cursor.onrender.com
    healthCheckPath: /_health
    autoDeploy: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1