services:
  - type: web
    name: rowdy-cup-api
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /_health
    autoDeploy: true 